### ISSUE TITLE
Add typing_extensions version to requirements

### ISSUE THREAD

**Issue by mojoe12** [ismrmrd/ismrmrd-python#77]
Hi team,

With an old typing_extensions version (4.5.0) I got this error when importing ismrmrd:

Traceback (most recent call last):
  File "examples/demo.py", line 1, in <module>
    import ismrmrd
  File "/home/jhutter/.local/lib/python3.8/site-packages/ismrmrd/__init__.py", line 7, in <module>
    from .file import File
  File "/home/jhutter/.local/lib/python3.8/site-packages/ismrmrd/file.py", line 8, in <module>
    from .xsd import ToXML
  File "/home/jhutter/.local/lib/python3.8/site-packages/ismrmrd/xsd/__init__.py", line 1, in <module>
    from .pyxb_compat import (CreateFromDocument, ToXML, ToDOM)
  File "/home/jhutter/.local/lib/python3.8/site-packages/ismrmrd/xsd/pyxb_compat.py", line 3, in <module>
    from xsdata.formats.dataclass.parsers import XmlParser
  File "/home/jhutter/.local/lib/python3.8/site-packages/xsdata/formats/dataclass/parsers/__init__.py", line 1, in <module>
    from xsdata.formats.dataclass.parsers.dict import DictDecoder
  File "/home/jhutter/.local/lib/python3.8/site-packages/xsdata/formats/dataclass/parsers/dict.py", line 9, in <module>
    from xsdata.formats.dataclass.context import XmlContext
  File "/home/jhutter/.local/lib/python3.8/site-packages/xsdata/formats/dataclass/context.py", line 7, in <module>
    from xsdata.formats.dataclass.models.builders import XmlMetaBuilder
  File "/home/jhutter/.local/lib/python3.8/site-packages/xsdata/formats/dataclass/models/builders.py", line 23, in <module>
    from xsdata.formats.dataclass.typing import (
  File "/home/jhutter/.local/lib/python3.8/site-packages/xsdata/formats/dataclass/typing.py", line 18, in <module>
    from typing_extensions import ForwardRef
ImportError: cannot import name 'ForwardRef' from 'typing_extensions' (/home/jhutter/.local/lib/python3.8/site-packages/typing_extensions.py)

It was fixed after upgrading typing_extensions to 4.12.0.
